sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 15327938768Lzy+

  minio:
    endpoint: http://74.48.39.246:9000/
    access-key: ahQuYa9khdLQgR1aruD6
    secret-key: knkjiAtUijY66Q38uKwqkFOrun9pruyWfNt71GOO
    bucket-name: sky-take-out
    expiry-time: 86400
  redis:
    host: localhost
    port: 6379
    database: 10